# Generated by Django 6.1.1 on 2026-09-16 10:34

import django.db.models.deletion
from django.db import migrations, models


def migrate_profile_sectors(apps, schema_editor):
    Profile = apps.get_model("core", "Profile")
    for profile in Profile.objects.exclude(sector__isnull=True).iterator():
        profile.member_sectors.add(profile.sector_id)
        if profile.role == "MANAGER":
            profile.managed_sectors.add(profile.sector_id)


def restore_profile_sector(apps, schema_editor):
    Profile = apps.get_model("core", "Profile")
    for profile in Profile.objects.all().iterator():
        sector = profile.member_sectors.first() or profile.managed_sectors.first()
        if sector:
            profile.sector_id = sector.id
            profile.unit_id = sector.unit_id
            profile.save(update_fields=["sector", "unit"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="managed_sectors",
            field=models.ManyToManyField(
                blank=True,
                related_name="manager_profiles",
                to="core.sector",
                verbose_name="setores gerenciados",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="member_sectors",
            field=models.ManyToManyField(
                blank=True,
                related_name="member_profiles",
                to="core.sector",
                verbose_name="setores membro",
            ),
        ),
        migrations.RunPython(migrate_profile_sectors, restore_profile_sector),
        migrations.RemoveField(
            model_name="profile",
            name="sector",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="unit",
        ),
        migrations.AlterField(
            model_name="task",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="core.unit",
            ),
        ),
    ]
